# Frontend Dockerfile
FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
# COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--poll=2000"]
